[project]
name = "dexcom-cli"
version = "0.1.0"
description = "A CLI for working with Dexcom CGM data directly from your terminal."
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "keyring>=25.7.0",
    "pydantic>=2.13.4",
    "pydexcom>=0.5.1",
    "python-dotenv>=1.2.2",
    "questionary>=2.1.1",
    "rich>=15.0.0",
    "typer>=0.26.8",
]

[project.scripts]
dexcom = "dexcom_cli.cli.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["src/dexcom_cli"]
